server:
  port: 8083
spring:
  rabbitmq:
    host: 192.168.41.156
    port: 5672
    username: xiaonan
    password: 123123
    virtual-host: /yingx
    listener:
      simple:
        prefetch: 1  #每个消费者每次可以消费一个